#!/bin/sh
echo ""
# sudo apt-get install curl
echo "curl ipinfo.io/$1"
/usr/bin/curl ipinfo.io/$1
echo ""
echo ""
# sudo apt-get install whois
echo "whois -h v4.whois.cymru.com -v $1"
/usr/bin/whois -h v4.whois.cymru.com -v $1
echo ""
echo ""
# sudo apt-get install geoip-bin
echo "geoiplookup $1"
/usr/bin/geoiplookup $1
echo ""
